### ISSUE TITLE
Englarge visualization of engineering constants and fix arrow tips

### ISSUE THREAD

**Issue by JulianKarlBauer** [JulianKarlBauer/mechkit#37]
Problems:
In [rendered docs](https://mechkit.readthedocs.io/en/latest/source/material_notes_engineeringConstants.html),
the svg-images show up 
- a bit small
- without arrow tips.

It might be good to
- [x] enlarge the images a bit
- [x] fix arrow tips.

It might be better to switch to png-files with low resolution (keep data small).

![Screenshot from 2022-02-18 11-08-08](https://user-images.githubusercontent.com/55383008/154662048-bdcb93ab-4577-46b2-b804-5766222737a2.png)

**Comment by philipplk** [comment]
can I refer to a merge request here?
I created one.

**Comment by JulianKarlBauer** [comment]
Thanks for handling this issue!
