### ISSUE TITLE
pytest not installed following README instructions

### ISSUE THREAD

**Issue by nicoguaro** [JulianKarlBauer/mechkit#46]
When you run

    python setup.py develop

Pytest is not installed and you can't run the test suite.

**Comment by JulianKarlBauer** [comment]
Hi nicoguaro, 
thank you for pointing this out. So far, this is intended behavior.
Why do you expect that installing in "develop"-mode would install pytest?


If I do `python setup.py develop` on the source code of [continuum_mechanics](https://github.com/nicoguaro/continuum_mechanics), test requirements are also not met, which from my personal point of view is fine.

If you point me towards an example where installing in develop mode is used to install test requirements, I rethink whether this is to be considered as a feature.

**Comment by JulianKarlBauer** [comment]
Another thought: The tests are run by Github-CI before pushing to PyPI. I don't think any user will run the tests. If so, instructions on running the tests are found in .github/workflow/... files. I think this procedure is quite common.

**Comment by nicoguaro** [comment]
I am not thinking as a user in this context but as a contributor. In that case, it is common practice to run tests locally before doing a PR. I would guess that's the public intended for that [information](https://github.com/JulianKarlBauer/mechkit/tree/master/test).

**Comment by JulianKarlBauer** [comment]
Thank you so much for reminding me on the contributor instructions on tests. Now I realize the problem. I added a note on installing pytest before running the tests. Are you fine with this solution? Please see #47 for a proposal.

**Comment by nicoguaro** [comment]
> Thank you so much for reminding me on the contributor instructions on tests. Now I realize the problem. I added a note on installing pytest before running the tests. Are you fine with this solution? Please see #47 for a proposal.

It looks OK to me.
